package dev.umbra.space_radar_api.models.dtos;

import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Data Transfer Object (DTO) representing the final prediction result from the
 * ML model.
 * *
 * <p>
 * This record encapsulates both the original physical characteristics of the
 * asteroid
 * and the synthetic data generated by the classification model, including
 * hazard
 * assessments and confidence metrics.
 * </p>
 *
 * @param id                     The unique identifier of the asteroid (NASA JPL
 *                               ID).
 * @param name                   The designation or common name of the asteroid.
 * @param isPotentiallyHazardous Boolean flag indicating if the ML model
 *                               classifies the
 *                               object as a threat.
 * @param confidenceScore        The probability or reliability of the
 *                               prediction,
 *                               typically ranging from 0.0 to 1.0.
 * @param status                 The operational status of the prediction
 *                               request
 *                               (e.g., "COMPLETED", "FAILED", "PENDING").
 * @param estDiameterMin         Minimum estimated diameter in kilometers.
 * @param estDiameterMax         Maximum estimated diameter in kilometers.
 * @param relativeVelocity       The speed of the asteroid relative to Earth
 *                               (km/h).
 * @param missDistance           The distance at which the asteroid passes Earth
 *                               (km).
 * @param absoluteMagnitude      The intrinsic luminosity (H) of the asteroid.
 * @param approachDate           The specific date of the closest approach.
 */
public record PredictionResponse(

        /** Unique identifier assigned to the asteroid. */
        int id,

        /** The primary name or designation of the celestial object. */
        String name,

        /**
         * * Classification result.
         * Maps to "is_hazardous" in JSON.
         */
        @JsonProperty("is_hazardous") boolean isPotentiallyHazardous,

        /**
         * * Model confidence metric.
         * Represents the softmax output or probability of the classification.
         */
        @JsonProperty("confidence_score") double confidenceScore,

        /**
         * * Lifecycle status of the specific prediction task.
         */
        @JsonProperty("status") String status,

        /** Minimum estimated diameter in kilometers. */
        @JsonProperty("est_diameter_min") double estDiameterMin,

        /** Maximum estimated diameter in kilometers. */
        @JsonProperty("est_diameter_max") double estDiameterMax,

        /** Relative velocity in km/h. */
        @JsonProperty("relative_velocity") double relativeVelocity,

        /** Miss distance in kilometers. */
        @JsonProperty("miss_distance") double missDistance,

        /** Absolute magnitude (H). */
        @JsonProperty("absolute_magnitude") double absoluteMagnitude,

        /** The date of the close approach event. */
        @JsonProperty("approach_date") LocalDate approachDate) {
}